source 'https://github.com/CocoaPods/Specs.git'

target 'ZCalendar' do
  pod "ZCalendar", :path => "../"
  
  # 二维绘图引擎ZQuartz
  pod 'UIView-ZQuartz', :git => 'https://github.com/zhuayi/UIView-ZQuartz.git'
end


